from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1373, 855)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.group_left = QtWidgets.QGroupBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.group_left.setFont(font)
        self.group_left.setTitle("")
        self.group_left.setObjectName("group_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.group_left)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.list_layers = QtWidgets.QListWidget(self.group_left)
        self.list_layers.setObjectName("list_layers")
        self.verticalLayout_2.addWidget(self.list_layers)
        self.widget_params = QtWidgets.QWidget(self.group_left)
        self.widget_params.setObjectName("widget_params")
        self.verticalLayout_2.addWidget(self.widget_params)
        self.group_center = QtWidgets.QGroupBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.group_center.setFont(font)
        self.group_center.setObjectName("group_center")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_center)
        self.verticalLayout.setObjectName("verticalLayout")
        self.canvas_container = QtWidgets.QWidget(self.group_center)
        self.canvas_container.setObjectName("canvas_container")
        self.verticalLayout.addWidget(self.canvas_container)
        self.group_right = QtWidgets.QGroupBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.group_right.setFont(font)
        self.group_right.setTitle("")
        self.group_right.setObjectName("group_right")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.group_right)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tree_tasks = QtWidgets.QTreeWidget(self.group_right)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.tree_tasks.setFont(font)
        self.tree_tasks.setObjectName("tree_tasks")
        self.verticalLayout_3.addWidget(self.tree_tasks)
        self.btn_generate_mask = QtWidgets.QPushButton(self.group_right)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.btn_generate_mask.setFont(font)
        self.btn_generate_mask.setObjectName("btn_generate_mask")
        self.verticalLayout_3.addWidget(self.btn_generate_mask)
        self.btn_extract_pheno = QtWidgets.QPushButton(self.group_right)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.btn_extract_pheno.setFont(font)
        self.btn_extract_pheno.setObjectName("btn_extract_pheno")
        self.verticalLayout_3.addWidget(self.btn_extract_pheno)
        self.verticalLayout_4.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1373, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_center.setTitle(_translate("MainWindow", "View"))
        self.tree_tasks.headerItem().setText(0, _translate("MainWindow", "1"))
        self.btn_generate_mask.setText(_translate("MainWindow", "Mask"))
        self.btn_extract_pheno.setText(_translate("MainWindow", "Pheno"))
